### ISSUE TITLE
Update broke plugin?

### ISSUE THREAD

**Issue by amau05** [tystuyfzand/gotify-smtp#7]
Hi,

When I try to install the last version of the plugin on my Gotify server 2.2.4, it crash, without the plugin it works fine but as soon as I put the plugin in and boot Gotify it won't work.

Didn't find any logs so I don't have specifics sorry.

Anyone else has the issue?

**Comment by tystuyfzand** [comment]
I'll test it soon, but make sure you have the right version (amd64, arm64, armv7) for your operating system

**Comment by amau05** [comment]
Yes I'm sure, I use the amd64 version, I double checked in case I had downloaded the arm64 version by mistake.

**Comment by tystuyfzand** [comment]
Testing it locally, I have Gotify 2.24 and the file "smtp-linux-amd64.so" installed. I'm able to load and use the Gotify plugin successfully, so I'd suggest simply removing all old versions of the plugin that may be there still, and re-downloading it.

**Comment by amau05** [comment]
Soo I'm sorry I checked again... I use gotify through a repo on qnap (myqnap) and the update actually failed or something like that which made the repo display the latest version but I was actually running an older one but it didn't worked the same as it was before as the reason I updated your plugin was because the old version was crashing gotify too... Don't know what actually happened but a clean install fixed the issue...
