### ISSUE TITLE
Update for Gotify v2.4.0

### ISSUE THREAD

**Issue by paulaylingdev** [tystuyfzand/gotify-smtp#8]
New version of gotify-server has been released: https://github.com/gotify/server/releases/tag/v2.4.0

The current version of the plugin is incompatible with it. 

Assuming the automatic build has not triggered.

I tested locally updating `GOTIFY_VERSION=v2.4.0` and the generated shared object file worked with the new server version.

**Comment by tystuyfzand** [comment]
Fixed, sorry! The server that watches for releases was having trouble.
